2020-10-22 16:52:37,384 ERROR: Exception on /edit_profile [GET] [in /Users/erniu/.local/share/virtualenvs/flask_demo-Y7zoDRtV/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/erniu/.local/share/virtualenvs/flask_demo-Y7zoDRtV/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/erniu/.local/share/virtualenvs/flask_demo-Y7zoDRtV/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/erniu/.local/share/virtualenvs/flask_demo-Y7zoDRtV/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/erniu/.local/share/virtualenvs/flask_demo-Y7zoDRtV/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/erniu/.local/share/virtualenvs/flask_demo-Y7zoDRtV/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/erniu/.local/share/virtualenvs/flask_demo-Y7zoDRtV/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/erniu/.local/share/virtualenvs/flask_demo-Y7zoDRtV/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/erniu/PycharmProjects/flask_demo/app/views.py", line 89, in edit_profile
    form = EditProfileForm()
  File "/Users/erniu/.local/share/virtualenvs/flask_demo-Y7zoDRtV/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2020-10-22 16:53:36,112 INFO: Microblog startup [in /Users/erniu/PycharmProjects/flask_demo/app/__init__.py:48]
